import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

/**
 * Frozen tier-2 checksums, so the cutover in #227 does not take the wasm libm
 * out of the gate with it.
 *
 * Tier 2 grades Rust against TypeScript, and #227 deletes the TypeScript. That
 * is not merely one of three tiers going away: **tier 2 is the only thing that
 * runs the port's arithmetic inside `wasm32-unknown-unknown`**. `cargo test`
 * links the host libm, so a `log2`/`pow` difference that exists only in the
 * wasm build is invisible to tier 1 - which is exactly what #270 was. The three
 * render specs do execute wasm, but only along paths that reach a rendered
 * pixel, and many fields reach none at all: the #226 comment lists Vulcanus's
 * `temperature`, its four resource favorabilities and the pre-volcano
 * `mountains_raw_volcano` stage as fields tier 3 says nothing whatever about.
 *
 * Freezing the folds keeps that coverage. Each parity spec asserts THREE things
 * where it used to assert one:
 *
 *   - the wasm fold equals the frozen value,
 *   - the TypeScript fold equals the frozen value,
 *   - and therefore the two agree, which is what the spec claimed before.
 *
 * While both ports exist the table cannot be wrong, because both arms are
 * checked against it. When the TypeScript arm goes, the wasm arm keeps running
 * against a value captured while the two demonstrably agreed. Tier 2 stops
 * being a comparison and becomes a regression baseline - it can no longer find
 * a NEW disagreement with a reference that no longer exists, but it still
 * catches the port moving, including underneath it in the toolchain.
 *
 * **Read a moved number, do not adjust it**, the same rule every frozen count
 * in this repo carries. A legitimate change (fixing #261, say) re-freezes
 * deliberately and says so; anything else is a regression.
 *
 * ## Recording
 *
 * The table is generated by the code that asserts it, so a hand-edit cannot
 * drift from what the specs actually fold:
 *
 * ```bash
 * FMW_FREEZE_TIER2=1 pnpm vp test test/wasmNauvisParity.spec.ts \
 *   test/wasmVulcanusParity.spec.ts test/wasmFulgoraParity.spec.ts
 * ```
 *
 * In record mode every `expectFrozen` call records instead of asserting, and
 * the file is rewritten on exit. Run the specs normally afterwards - a record
 * run proves nothing, because in it nothing is compared.
 */

const TABLE_PATH = join(import.meta.dirname, "fixtures", "tier2-checksums.json");

/** Set to record rather than assert. See the module comment. */
export const RECORDING = process.env.FMW_FREEZE_TIER2 === "1";

type Table = Record<string, Record<string, string>>;

function load(): Table {
  if (!existsSync(TABLE_PATH)) return {};
  return JSON.parse(readFileSync(TABLE_PATH, "utf8")) as Table;
}

const table: Table = RECORDING ? {} : load();
const recorded: Table = {};

/**
 * u64 as a zero-padded hex string. JSON has no integer wide enough to hold one
 * of these exactly - `2n ** 64n` is far past `Number.MAX_SAFE_INTEGER`, so a
 * JSON number would silently round and the table would freeze the wrong value.
 */
function toHex(v: bigint): string {
  return `0x${v.toString(16).padStart(16, "0")}`;
}

let dirty = false;

/**
 * The frozen value for one (planet, case, field), or `undefined` when the table
 * has no entry - which a caller must treat as a failure, never as a pass.
 */
export function frozen(planet: string, label: string, field: string): bigint | undefined {
  const hex = table[planet]?.[`${label} | ${field}`];
  return hex === undefined ? undefined : BigInt(hex);
}

/**
 * Record one checksum under record mode. Returns true when recording, so a
 * caller can skip its assertions.
 */
export function record(planet: string, label: string, field: string, value: bigint): void {
  (recorded[planet] ??= {})[`${label} | ${field}`] = toHex(value);
  dirty = true;
}

/** Number of entries the table holds for one planet. */
export function frozenCount(planet: string): number {
  return Object.keys(table[planet] ?? {}).length;
}

/**
 * Merge this run's recordings into the committed table and write it out. Called
 * from an `afterAll` in each parity spec, so a partial run only rewrites the
 * planets it actually swept rather than truncating the other two.
 */
export function flushRecording(): void {
  if (!RECORDING || !dirty) return;
  const merged: Table = load();
  for (const [planet, rows] of Object.entries(recorded)) merged[planet] = rows;
  const ordered: Table = {};
  for (const planet of Object.keys(merged).sort()) {
    const rows = merged[planet] as Record<string, string>;
    const sorted: Record<string, string> = {};
    for (const k of Object.keys(rows).sort()) sorted[k] = rows[k] as string;
    ordered[planet] = sorted;
  }
  mkdirSync(dirname(TABLE_PATH), { recursive: true });
  writeFileSync(TABLE_PATH, `${JSON.stringify(ordered, null, 2)}\n`);
}
