import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

/**
 * Frozen tier-2 checksums, so the cutover in #227 does not take the wasm libm
 * out of the gate with it.
 *
 * Tier 2 grades Rust against TypeScript, and #227 deletes the TypeScript. That
 * is not merely one of three tiers going away: **tier 2 is the only thing that
 * runs the port's arithmetic inside `wasm32-unknown-unknown`**. `cargo test`
 * links the host libm, so a `log2`/`pow` difference that exists only in the
 * wasm build is invisible to tier 1 - which is exactly what #270 was. The three
 * render specs do execute wasm, but only along paths that reach a rendered
 * pixel, and many fields reach none at all: the #226 comment lists Vulcanus's
 * `temperature`, its four resource favorabilities and the pre-volcano
 * `mountains_raw_volcano` stage as fields tier 3 says nothing whatever about.
 *
 * Freezing the folds keeps that coverage. Each parity spec asserts THREE things
 * where it used to assert one:
 *
 *   - the wasm fold equals the frozen value,
 *   - the TypeScript fold equals the frozen value,
 *   - and therefore the two agree, which is what the spec claimed before.
 *
 * While both ports exist the table cannot be wrong, because both arms are
 * checked against it. When the TypeScript arm goes, the wasm arm keeps running
 * against a value captured while the two demonstrably agreed. Tier 2 stops
 * being a comparison and becomes a regression baseline - it can no longer find
 * a NEW disagreement with a reference that no longer exists, but it still
 * catches the port moving, including underneath it in the toolchain.
 *
 * **Read a moved number, do not adjust it**, the same rule every frozen count
 * in this repo carries. A legitimate change (fixing #261, say) re-freezes
 * deliberately and says so; anything else is a regression.
 *
 * ## Recording
 *
 * The table is generated by the code that asserts it, so a hand-edit cannot
 * drift from what the specs actually fold:
 *
 * ```bash
 * FMW_FREEZE_TIER2=1 pnpm vp test test/wasmNauvisParity.spec.ts \
 *   test/wasmVulcanusParity.spec.ts test/wasmFulgoraParity.spec.ts
 * ```
 *
 * In record mode every `expectFrozen` call records instead of asserting, and
 * the file is rewritten on exit. Run the specs normally afterwards - a record
 * run proves nothing, because in it nothing is compared.
 */

const TABLE_PATH = join(import.meta.dirname, "fixtures", "tier2-checksums.json");

/** Set to record rather than assert. See the module comment. */
export const RECORDING = process.env.FMW_FREEZE_TIER2 === "1";

type Table = Record<string, Record<string, string>>;

function load(): Table {
  if (!existsSync(TABLE_PATH)) return {};
  return JSON.parse(readFileSync(TABLE_PATH, "utf8")) as Table;
}

const table: Table = RECORDING ? {} : load();
const recorded: Table = {};

/**
 * u64 as a zero-padded hex string. JSON has no integer wide enough to hold one
 * of these exactly - `2n ** 64n` is far past `Number.MAX_SAFE_INTEGER`, so a
 * JSON number would silently round and the table would freeze the wrong value.
 */
function toHex(v: bigint): string {
  return `0x${v.toString(16).padStart(16, "0")}`;
}

let dirty = false;

/**
 * The frozen value for one (planet, case, field), or `undefined` when the table
 * has no entry - which a caller must treat as a failure, never as a pass.
 */
export function frozen(planet: string, label: string, field: string): bigint | undefined {
  const hex = table[planet]?.[`${label} | ${field}`];
  return hex === undefined ? undefined : BigInt(hex);
}

/**
 * Record one checksum under record mode. Returns true when recording, so a
 * caller can skip its assertions.
 */
export function record(planet: string, label: string, field: string, value: bigint): void {
  (recorded[planet] ??= {})[`${label} | ${field}`] = toHex(value);
  dirty = true;
}

/**
 * Every frozen row name, grouped by planet.
 *
 * Exists for `tier2Coverage.spec.ts`, which enumerates the module's actual
 * exports and checks each has a row. Reading the table rather than any spec's
 * case list is the point: a check sourced from the same array it validates can
 * only catch a deletion, never an omission.
 */
export function frozenNames(): [string, string[]][] {
  return Object.entries(table).map(([planet, rows]) => [planet, Object.keys(rows)]);
}

/** Number of entries the table holds for one planet. */
export function frozenCount(planet: string): number {
  return Object.keys(table[planet] ?? {}).length;
}

/**
 * Assert one fold against its frozen value, and against the reference arm while
 * that arm still exists.
 *
 * This is the conversion #227 needs applied to every Rust-vs-TypeScript
 * assertion: `expect(wasm).toBe(tsFold)` becomes
 * `expectFrozen(planet, label, name, wasm, tsFold)`. While both ports exist all
 * three agree, so the table cannot be wrong. When the TypeScript arm goes the
 * call drops its last argument and the wasm arm keeps running against a value
 * captured while the two demonstrably agreed.
 *
 * **Converting the existing parity specs rather than writing fresh minimal ones
 * was the second attempt, and the first was wrong.** A hand-written spec that
 * picked one case per export looked equivalent and was not: three review rounds
 * found nine cases whose ARGUMENTS never reached the branch the op exists to
 * get right - a `pow` sweep that missed the exact-sqrt path, a spot selection
 * fixed on constant favorability so the sort comparator was unobservable, an
 * `eval_math` range entirely below its clamp, a seed sweep that never wrapped.
 * Those specs' constants ARE the coverage. Carry them; do not reinvent them.
 */
export function expectFrozen(
  planet: string,
  label: string,
  name: string,
  wasm: bigint,
  reference?: bigint,
): void {
  const where = `${label}: ${name}`;
  if (RECORDING) {
    if (reference !== undefined && wasm !== reference) {
      throw new Error(`${where}: refusing to record, arms disagree - ${wasm} vs ${reference}`);
    }
    record(planet, label, name, wasm);
    return;
  }
  const want = frozen(planet, label, name);
  if (want === undefined) throw new Error(`${where}: no frozen checksum`);
  if (wasm !== want) throw new Error(`${where}: wasm ${wasm} != frozen ${want}`);
  if (reference !== undefined && reference !== want) {
    throw new Error(`${where}: reference ${reference} != frozen ${want}`);
  }
}

/**
 * Declare how many rows this planet's sweep must record before the table is
 * rewritten. Call it ONCE per planet, at module scope.
 *
 * **Without this a FAILED record run writes a partial table**, which is not
 * hypothetical - it happened twice while this file was being written. A
 * divergence part-way through the sweep throws, `afterAll` still runs, and the
 * table lands holding 502 of its 504 rows. The next normal run then fails on a
 * missing entry, which reads like a second unrelated break rather than like the
 * first one's wreckage.
 *
 * It is a COUNT rather than a flag because a planet can record across more than
 * one test - Vulcanus folds its three windows in one and its off-grid window in
 * another - so "this test finished" is not the same as "the sweep is whole".
 *
 * **The total is one module-scope declaration, and calling this twice is an
 * error rather than a sum.** An earlier version accumulated, so a spec could
 * declare per-block counts. That opened the hole this guard exists to close: a
 * block that never runs - filtered out by `-t`, or throwing before its own call
 * - leaves `recorded` AND `expected` short by exactly the same amount, so the
 * count check passes and `flushRecording` rewrites the section with only the
 * rows that ran. Measured, not reasoned: under accumulate,
 * `FMW_FREEZE_TIER2=1 pnpm vp test test/wasmEvalParity.spec.ts -t "slider"`
 * exited 0 having cut `primitives:eval` from 16 rows to 5.
 *
 * A single declaration that no filter can skip is what makes a short run fall
 * short of its own total, which is the condition `flushRecording` acts on.
 *
 * The five primitive specs pass a literal, because their totals span blocks and
 * two of them come from loop counters, so there is nothing to derive it from.
 * That buys a second guard for free: adding a case makes a record run DROP the
 * planet until someone updates the number. The three planet specs derive theirs
 * from `FIELD_NAMES` and their case tables instead, which is better there -
 * `FIELD_NAMES` is already checked against the module's own
 * `<planet>_field_count()` export, so the derived form inherits that check.
 */
export function expectRecordedRows(planet: string, rows: number): void {
  const already = expected.get(planet);
  if (already !== undefined) {
    throw new Error(
      `${planet}: row total declared twice (${already} then ${rows}) - declare it once, ` +
        `at module scope, as the whole planet's total`,
    );
  }
  expected.set(planet, rows);
}

const expected = new Map<string, number>();

/**
 * Merge this run's recordings into the committed table and write it out. Called
 * from an `afterAll` in each parity spec, so a partial run only rewrites the
 * planets it actually swept rather than truncating the other two.
 *
 * A planet that recorded fewer rows than it declared is DROPPED rather than
 * written, so a run that threw part-way leaves the committed table untouched.
 */
export function flushRecording(): void {
  if (!RECORDING || !dirty) return;
  for (const [planet, rows] of Object.entries(recorded)) {
    const want = expected.get(planet);
    if (want === undefined || Object.keys(rows).length !== want) delete recorded[planet];
  }
  if (Object.keys(recorded).length === 0) return;
  const merged: Table = load();
  for (const [planet, rows] of Object.entries(recorded)) merged[planet] = rows;
  const ordered: Table = {};
  for (const planet of Object.keys(merged).sort()) {
    const rows = merged[planet] as Record<string, string>;
    const sorted: Record<string, string> = {};
    for (const k of Object.keys(rows).sort()) sorted[k] = rows[k] as string;
    ordered[planet] = sorted;
  }
  mkdirSync(dirname(TABLE_PATH), { recursive: true });
  writeFileSync(TABLE_PATH, `${JSON.stringify(ordered, null, 2)}\n`);
}
