/**
 * The Nauvis rocks placement-probability field: `clamp(max_i probability_i, 0, 1)`
 * over the three charted rock prototypes (huge-rock, big-rock, big-sand-rock).
 * Per-tile arbitration is max probability (docs/noise/placement-roll-NOTES.md), so
 * the max is exact - it is the probability the game rolls where a rock wins.
 *
 * probability = multiplier * control:rocks:size * (region_box + rock_density - penalty)
 * See rockCatalog.ts / the plan header for the per-prototype constants.
 *
 * **Why exactly three prototypes.** `base/prototypes/decorative/decoratives.lua`
 * (2.1.12) gives EIGHT prototypes `autoplace.control = "rocks"`, but five of them
 * - medium-rock, small-rock, tiny-rock, medium-sand-rock, small-sand-rock - are
 * `type = "optimized-decorative"`. Decoratives are generated by a different pass
 * and are not entities, so they neither appear in the game's entity counts nor
 * compete in the entity placement arbitration. The three that are
 * `type = "simple-entity"` are exactly huge-rock, big-rock and big-sand-rock.
 *
 * `renderRocks.ts` rolls this field through `makePlacementSet` rather than
 * thresholding it; the per-prototype probabilities are exposed by
 * {@link makeRockFields} because the collision gate needs the winning
 * prototype's box, and unlike Vulcanus the Nauvis argmax is NOT degenerate.
 */
import { clamp } from "../eval/math";
import { sliderRescale } from "../eval/sliderRescale";
import { distanceFromNearestPoint, type Point } from "../distanceFromNearestPoint";
import { makeAux } from "../expressions/aux";
import { makeMoisture } from "../expressions/moisture";
import { makeMultioctaveNoise } from "../multioctaveNoise";
import { rangeSelectBase, ROCK_SEED1 } from "./rockCatalog";

export interface RockFieldParams {
  /** Map seed (= map_seed / seed0). */
  readonly seed0: number;
  /** control:rocks:frequency; default 1. */
  readonly rocksFrequency?: number;
  /** control:rocks:size; default 1. */
  readonly rocksSize?: number;
  /** control:water:frequency; default 1. Threads into moisture/aux shared noise. */
  readonly segmentationMultiplier?: number;
  readonly moistureFrequency?: number;
  readonly moistureBias?: number;
  readonly auxFrequency?: number;
  readonly auxBias?: number;
  readonly startingAreaMoistureSize?: number;
  readonly startingAreaMoistureFrequency?: number;
  /** Spawn points for `distance`. Default single origin spawn. */
  readonly startingPositions?: readonly Point[];
}

/** The three Nauvis rock prototypes' probabilities at one tile, unclamped. */
export interface RockProbabilities {
  /** `huge-rock`'s autoplace probability. */
  readonly huge: number;
  /** `big-rock`'s autoplace probability. */
  readonly big: number;
  /** `big-sand-rock`'s autoplace probability. */
  readonly sand: number;
}

export interface RockFields {
  /**
   * `clamp(max(huge, big, sand), 0, 1)` - what the overlay's placement roll rolls
   * against. Allocation-free; this is the per-tile hot path.
   */
  readonly density: (x: number, y: number) => number;
  /**
   * The three probabilities separately, for picking the winning prototype's
   * collision box. Allocates, and is only meant to be called on tiles that have
   * already passed both the roll and the water gate - 252 of 262144 tiles
   * (0.096%) in oracle region 0 and 60 of 262144 (0.023%) in region 1, measured;
   * see the table on `makeNauvisRockPlacement`.
   */
  readonly at: (x: number, y: number) => RockProbabilities;
}

/** Build the Nauvis rock probability fields for one seed and set of levers. */
export function makeRockFields(params: RockFieldParams): RockFields {
  const seed0 = params.seed0;
  const freq = params.rocksFrequency ?? 1;
  const size = params.rocksSize ?? 1;
  const spawn: readonly Point[] = params.startingPositions ?? [{ x: 0, y: 0 }];

  const noise = makeMultioctaveNoise({
    seed0,
    seed1: ROCK_SEED1,
    octaves: 4,
    persistence: 0.9,
    inputScale: 0.15 * freq,
    outputScale: 1,
  });
  const moisture = makeMoisture({
    seed0,
    segmentationMultiplier: params.segmentationMultiplier,
    moistureFrequency: params.moistureFrequency,
    moistureBias: params.moistureBias,
    startingAreaMoistureSize: params.startingAreaMoistureSize,
    startingAreaMoistureFrequency: params.startingAreaMoistureFrequency,
    startingPositions: [...spawn],
  });
  const aux = makeAux({
    seed0,
    segmentationMultiplier: params.segmentationMultiplier,
    frequency: params.auxFrequency,
    bias: params.auxBias,
  });

  // control:rocks:size enters twice: as the outer multiplier and inside rock_noise
  // via slider_rescale. sizeTerm is the size-dependent, position-independent tail
  // of rock_noise, hoisted out of the per-pixel loop.
  const sizeTerm = 0.25 + 0.75 * (sliderRescale(size, 1.5) - 1);

  // Written by `evalParts` and read immediately by its two callers. Closure
  // scratch rather than a returned object so `density` - which every tile of
  // every chunk goes through - allocates nothing.
  let pHuge = 0;
  let pBig = 0;
  let pSand = 0;

  const evalParts = (x: number, y: number): void => {
    const rockNoise = noise(x, y) + sizeTerm;
    const distance = distanceFromNearestPoint(x, y, spawn);
    const rockDensity = rockNoise - Math.max(0, 1.1 - distance / 32);

    const m = moisture(x, y);
    const moistBand = rangeSelectBase(m, 0.35, 1, 0.2, -10, 0);
    pHuge = 0.07 * size * (moistBand + rockDensity - 1.7);
    pBig = 0.17 * size * (moistBand + rockDensity - 1.6);

    const a = aux(x, y);
    const sandBand = Math.min(
      rangeSelectBase(a, 0.3, 1, 0.3, -10, 0),
      rangeSelectBase(m, 0, 0.3, 0.2, -10, 0),
    );
    pSand = 0.1 * size * (sandBand + rockDensity - 1.6);
  };

  return {
    density: (x, y) => {
      evalParts(x, y);
      return clamp(Math.max(pHuge, pBig, pSand), 0, 1);
    },
    at: (x, y) => {
      evalParts(x, y);
      return { huge: pHuge, big: pBig, sand: pSand };
    },
  };
}

/** `makeRockFields(params).density` - the field on its own. */
export function makeRockDensity(params: RockFieldParams): (x: number, y: number) => number {
  return makeRockFields(params).density;
}
