/**
 * Regenerate `src/noise/basisGradientTable.ts`.
 *
 * Run with: node --experimental-strip-types scripts/gen-gradient-table.ts
 *
 * The table is COMMITTED rather than derived at load, and that is a
 * correctness control rather than a startup optimisation. Two reasons:
 *
 * 1. **`Math.cos` is not portable in the last bit.** #214 measured V8's
 *    `Math.cos`/`Math.sin` differing from libm on the same inputs (gradient
 *    table checksums `bc9a79394c9e8930` against `bc9a79394c9e8ae3`). A table
 *    derived at load therefore depends on which engine runs the code.
 * 2. **The Rust port has to agree bit for bit.** Rust would derive this table
 *    with libm, so a load-time derivation would put a last-bit disagreement
 *    under every planet on both sides - which is exactly the gate the port
 *    depends on (spec section 7, tier 2).
 *
 * The formula below is not a guess. It was picked by sweeping 384 kernel and
 * table variants against both committed fixtures and scoring by EXACT f32
 * match count, not by an error bound - every value in both fixtures is exactly
 * f32, so a bit-exact port reproduces them exactly and a bound cannot tell
 * "close" from "identical". Results on `basis-noise.seed123456.json`:
 *
 * | table construction                            | exact   | worst   |
 * | --------------------------------------------- | ------- | ------- |
 * | f64 angle, f64 trig, *4.2, narrow (old shape) | 208/512 | 2.682e-7 |
 * | f64 angle, narrowed trig, *f32(4.2)           | 147/512 | 2.533e-7 |
 * | f32 angle, narrowed trig, *f32(4.2)           | 234/512 | 2.384e-7 |
 * | **f32 angle, trig then *4.2, ONE narrowing**  | **473/512** | **1.192e-7** |
 *
 * So the angle is computed in f32 and everything after it rounds once. The
 * remaining 39 points are 1-2 ULP apart bar a few near-zero cancellations,
 * which is consistent with the game's own table coming from a minimax
 * polynomial (`docs/noise/basis-noise-NOTES.md`) rather than from libm.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const TABLE_SIZE = 256;
const GRADIENT_MAGNITUDE = 4.2;
const f = Math.fround;

/** The f32 angle for slot `h`. Narrowing HERE is what the sweep selected. */
const angle = (h: number): number => f((2 * Math.PI * h) / TABLE_SIZE);

const gx = Array.from({ length: TABLE_SIZE }, (_, h) => f(Math.cos(angle(h)) * GRADIENT_MAGNITUDE));
const gy = Array.from({ length: TABLE_SIZE }, (_, h) => f(Math.sin(angle(h)) * GRADIENT_MAGNITUDE));

/**
 * The shortest decimal that narrows back to the same f32.
 *
 * Not cosmetic. A default `${v}` prints the shortest round-trip for the f64,
 * which for these values runs to 17 significant digits - more than f64
 * represents exactly, so `eslint(no-loss-of-precision)` flags it. Every f32
 * needs at most 9, and any f64 within half an f32 ULP narrows to the same f32,
 * so this is exact where it matters: `new Float32Array([...])` stores the
 * identical bits. Asserted per entry below before anything is written.
 */
const shortestF32Literal = (v: number): string => {
  for (let digits = 1; digits <= 17; digits++) {
    const candidate = Number(v.toPrecision(digits));
    if (f(candidate) === v) return String(candidate);
  }
  throw new Error(`no round-tripping literal for ${v}`);
};

const column = (values: number[]): string => {
  const lines: string[] = [];
  for (let i = 0; i < values.length; i += 4) {
    lines.push(
      "  " +
        values
          .slice(i, i + 4)
          .map((v) => `${shortestF32Literal(v)},`)
          .join(" "),
    );
  }
  return lines.join("\n");
};

const body = `/**
 * The \`basis_noise\` gradient table, with the magnitude folded in.
 *
 * GENERATED by scripts/gen-gradient-table.ts - do not hand-edit. Read that
 * file for why these are committed constants rather than \`Math.cos\` calls at
 * load, and for the measurement that picked the formula.
 *
 * Slot \`h\` holds \`f32(cos(f32(2*pi*h/256)) * 4.2)\` and the matching sine. The
 * 4.2 is the gradient magnitude, measured at 4.19999919 +/- 1.4e-6 across 9216
 * lattice points; folding it into the table rather than multiplying by it at
 * evaluation time is what the game does, and the fixtures discriminate:
 * folded scores 166/512 exact against 123/512 for a separate multiply, at the
 * same fold order.
 *
 * A \`Float32Array\` rather than a plain array so the element type states the
 * invariant instead of a comment claiming it.
 */
export const GRADIENT_X = new Float32Array([
${column(gx)}
]);

export const GRADIENT_Y = new Float32Array([
${column(gy)}
]);
`;

const out = join(import.meta.dirname, "..", "src", "noise", "basisGradientTable.ts");
writeFileSync(out, body);
console.log(`wrote ${out}`);
console.log(`gx[0]=${gx[0]} gx[64]=${gx[64]} gy[64]=${gy[64]} gx[128]=${gx[128]}`);
