//! The request encoding and the render buffer - the whole of the boundary's
//! data layout, and nothing that computes anything.
//!
//! Design record: section 6 of
//! `docs/superpowers/specs/2026-08-16-rust-wasm-noise-engine-design.md`.
//!
//! ## Why hand-written on both sides
//!
//! A TypeScript writer and a Rust reader, both by hand, with no dependency
//! either side. The alternative - a schema compiler - would add a build step to
//! a repo whose whole deployment story is that `vp build` needs no non-JS step,
//! and a generated reader is not obviously easier to review than 60 lines of
//! `from_le_bytes`.
//!
//! What keeps them in step instead:
//!
//! - **A magic word and a version word.** A mismatch is a hard error with its
//!   own status code, not a best-effort parse of whatever arrived.
//! - **Committed round-trip fixtures**, one per planet.
//!   `test/fixtures/wasm-request.v2.json` carries a known request of each shape,
//!   its exact bytes, and the fields they decode to. Neither side can change a
//!   layout without the other going red, and the bytes are in the repository
//!   rather than being regenerated by the thing under test.
//! - **The sizes are exported.** `request_bytes()` reports the LARGEST request
//!   the module can accept, and the per-planet block sizes below are the single
//!   definition; the TypeScript writer asserts against them.
//!
//! ## v2: a common prefix, then a planet-specific block
//!
//! v1 was one fixed 104-byte struct with Fulgora's two island sliders and four
//! trig values baked into it. Vulcanus needs 31 more `f64` - three volcanism and
//! temperature levers, eight resource-control values, and twenty trig values for
//! its ten per-render bearings - and Nauvis will need its own set again.
//!
//! Folding all of them into one struct would work and would be a smaller diff,
//! but it grows once per planet and leaves every Fulgora request carrying 248
//! bytes of zeros. So v2 splits the layout: a fixed common prefix that every
//! planet shares, then a block whose length the prefix declares. v1's `reserved`
//! word becomes `params_bytes`, which is what its own comment said it was there
//! for.
//!
//! `params_bytes` is declared rather than inferred from the planet code on
//! purpose. It means a short or overlong block is caught by the decoder as a
//! length error, at the boundary, instead of being read as whatever the next
//! bytes happen to be.
//!
//! Little-endian throughout - the byte order WebAssembly specifies for its own
//! loads, so no swapping happens on any host.
//!
//! Every `u32` comes first, padded to a multiple of 8, so every `f64` lands on
//! an 8-byte boundary. Nothing here reads through an aligned pointer - the
//! decode is `from_le_bytes` over a slice - so this buys nothing at runtime. It
//! buys a `DataView` writer on the TypeScript side that a reader can check by
//! eye against a hexdump.
//!
//! ```text
//! common prefix
//!   0  u32  magic          'FMWR' little-endian
//!   4  u32  abi_version
//!   8  u32  planet         0 = fulgora, 1 = vulcanus
//!  12  u32  view           0 = landmask, 1 = terrain, 2 = scrap footprint
//!  16  u32  seed0          the SURFACE seed, not the map seed
//!  20  u32  width
//!  24  u32  height
//!  28  u32  params_bytes   length of the planet block that follows
//!  32  f64  origin_x
//!  40  f64  origin_y
//!  48  f64  tiles_per_pixel
//!  56  = COMMON_BYTES
//!
//! fulgora block (48 bytes, so a Fulgora request is 104 - unchanged from v1)
//!  +0  f64  islands_frequency
//!  +8  f64  islands_size
//! +16  f64  sin_start      sine of the starting bearing
//! +24  f64  cos_start
//! +32  f64  sin_vault      sine of the vault bearing (the starting one + 180)
//! +40  f64  cos_vault
//!
//! vulcanus block (312 bytes, so a Vulcanus request is 368)
//!  +0  f64  volcanism_frequency
//!  +8  f64  volcanism_size
//! +16  f64  temperature_bias
//! +24  f64  tungsten_frequency
//! +32  f64  tungsten_size
//! +40  f64  coal_frequency
//! +48  f64  coal_size
//! +56  f64  calcite_frequency
//! +64  f64  calcite_size
//! +72  f64  sulfur_frequency
//! +80  f64  sulfur_size
//! +88  f64 x 20  trig, as ten (sin, cos) pairs in TRIG ORDER below
//! +248 f64 x 4   cell_query_box: x0, y0, x1, y1
//! +280 f64 x 4   placement_sweep_box: x0, y0, x1, y1
//! ```
//!
//! **The Vulcanus block has grown twice with no version bump - 248 to 280 for
//! the cliff view, 280 to 312 for the rock and resource overlays - and that is
//! the split working rather than a shortcut.** The prefix declares its own
//! block length, [`Status::BadParamsLength`] refuses a writer that disagrees
//! with it, and Fulgora's request has not moved a byte through either change.
//! Both halves ship together in this repository and
//! `test/fixtures/wasm-request.v2.json` pins the encoding for each planet, so
//! there is no third party whose old requests could still be in flight. A
//! version bump is for a change to the COMMON prefix, which every planet
//! reads.
//!
//! **Two boxes, not one, because their halos are different shapes.** The cliff
//! block spans `px - 2 ..= px + 1`, which is asymmetric and whose two
//! directions CROSS; the placement mark is a 3x3 centred on its pixel, which is
//! symmetric. Deriving either one here would need the FULL image's geometry,
//! which the common prefix does not carry and only the tiled renderer knows -
//! so both are sent, and `haloQueryBox` on the TypeScript side stays the one
//! place that arithmetic lives.
//!
//! **The trig fields are the unusual part and they are deliberate.** Every angle
//! is a per-render constant at every call site, and `starting_spot_at_angle` has
//! no f32 narrowing to absorb a one-ULP `sin` difference - which #270 measured
//! really does exist between V8 and the libm `wasm32-unknown-unknown` links, in
//! a place `cargo test` on the host cannot see. Passing the values instead of
//! the angles makes that impossible rather than unlikely. Vulcanus needs ten
//! bearings where Fulgora needs two, which is most of why its block is five
//! times the size. See `fmw_noise::expressions::starting_spot_at_angle`.

/// `'FMWR'` little-endian.
pub const MAGIC: u32 = 0x5257_4d46;

/// The layout version. Bump it for ANY change to the tables above.
pub const ABI_VERSION: u32 = 2;

/// Size of the common prefix, in bytes.
pub const COMMON_BYTES: usize = 56;

/// Size of Fulgora's parameter block.
pub const FULGORA_PARAMS_BYTES: usize = 48;

/// Size of Vulcanus's parameter block.
pub const VULCANUS_PARAMS_BYTES: usize = 312;

/// The largest request the module can accept, which is what `request_bytes()`
/// reports so a caller can size one buffer for every planet.
pub const REQUEST_BYTES: usize = COMMON_BYTES + VULCANUS_PARAMS_BYTES;

/// `planet` code for Fulgora.
pub const PLANET_FULGORA: u32 = 0;
/// `planet` code for Vulcanus.
pub const PLANET_VULCANUS: u32 = 1;

/// The ten Vulcanus bearings, in the order their `(sin, cos)` pairs appear in
/// the block.
///
/// Written as an enum rather than as bare indices so a caller and the decoder
/// cannot disagree about which pair is which. Getting two of these the wrong way
/// round produces a perfectly plausible planet with its biomes rotated, which no
/// bound and no smoke test would catch.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(usize)]
pub enum VulcanusBearing {
    SpawnAshlands = 0,
    SpawnMountains = 1,
    SpawnBasalts = 2,
    BiomeVolcanoSpot = 3,
    BiomeProtector = 4,
    ResourceTungsten = 5,
    ResourceCoal = 6,
    ResourceCalcite = 7,
    ResourceSulfurFar = 8,
    ResourceSulfurNear = 9,
}

/// How many bearings Vulcanus sends.
pub const VULCANUS_BEARINGS: usize = 10;

/// What a decode can go wrong with.
///
/// Returned as a status code rather than trapping. A trap would poison the
/// instance for every later request in that worker, and expected errors are
/// expected - see spec section 6.5.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum Status {
    Ok = 0,
    ShortBuffer = 1,
    BadMagic = 2,
    BadVersion = 3,
    UnsupportedPlanetOrView = 4,
    OutputTooLarge = 5,
    /// The declared `params_bytes` is not what this planet's block measures.
    ///
    /// v1's `ReservedNotZero` occupied this code. The reserved word BECAME
    /// `params_bytes`, so the check that word carries became a length check -
    /// same slot, same code, same job of refusing a writer that disagrees with
    /// its own version word.
    BadParamsLength = 6,
}

/// A decoded render request: the common prefix plus whichever block arrived.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Request {
    pub planet: u32,
    pub view: u32,
    pub seed0: u32,
    pub width: u32,
    pub height: u32,
    pub origin_x: f64,
    pub origin_y: f64,
    pub tiles_per_pixel: f64,
    pub params: Params,
}

/// The planet-specific half.
///
/// `large_enum_variant` is allowed rather than obeyed. Its advice is to box the
/// Vulcanus block, which would put an allocation and a pointer indirection on
/// the render path to save 232 bytes of stack in a function that runs ONCE per
/// request - and it would make [`Request`] no longer `Copy`, which the render
/// loop relies on. The asymmetry is the planets', not a modelling mistake:
/// Vulcanus genuinely needs ten bearings where Fulgora needs two.
#[derive(Debug, Clone, Copy, PartialEq)]
#[allow(clippy::large_enum_variant)]
pub enum Params {
    Fulgora(FulgoraParams),
    Vulcanus(VulcanusParams),
}

/// Fulgora's block.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct FulgoraParams {
    pub islands_frequency: f64,
    pub islands_size: f64,
    pub sin_start: f64,
    pub cos_start: f64,
    pub sin_vault: f64,
    pub cos_vault: f64,
}

/// Vulcanus's block.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct VulcanusParams {
    pub volcanism_frequency: f64,
    pub volcanism_size: f64,
    pub temperature_bias: f64,
    pub tungsten_frequency: f64,
    pub tungsten_size: f64,
    pub coal_frequency: f64,
    pub coal_size: f64,
    pub calcite_frequency: f64,
    pub calcite_size: f64,
    pub sulfur_frequency: f64,
    pub sulfur_size: f64,
    /// Ten `(sin, cos)` pairs, indexed by [`VulcanusBearing`].
    pub trig: [(f64, f64); VULCANUS_BEARINGS],
    /// The world box to enumerate cliff cells over, as `[x0, y0, x1, y1]`.
    ///
    /// **Sent rather than derived, and that is not laziness.** A cliff cell
    /// paints a 4px block spanning `px - 2 ..= px + 1`, so a cell centred just
    /// outside a worker tile still owes that tile pixels - and the halo is
    /// ASYMMETRIC and the two directions CROSS: a mark reaching far backwards
    /// has to be caught from ahead of the tile. Deriving that here would need
    /// the full image's geometry, which the common prefix does not carry and
    /// which only the tiled renderer knows.
    ///
    /// It is also where the tiled-vs-whole cost lives. The cliff pass quantises
    /// its enumeration to 32-tile chunks, so one surplus tile of halo can pull
    /// in a whole extra chunk per axis - a symmetric 2/2 halo measured 24,336
    /// cliffiness evaluations against 17,424 for the exact 1/2 one, 1.40x for
    /// zero pixels of difference. Keeping the exact box on the TypeScript side
    /// keeps that in the one place `test/tiledEquality.spec.ts` already guards.
    ///
    /// For an untiled render this is the pixel box itself.
    pub cell_query_box: [f64; 4],
    /// The world box to sweep for placement-roll hits, as `[x0, y0, x1, y1]`.
    ///
    /// The rock and geyser overlays paint a 3x3 mark centred on the hit's
    /// pixel, so a hit centred just outside a worker tile still owes that tile
    /// pixels. Unlike [`VulcanusParams::cell_query_box`] this halo really IS
    /// symmetric and cannot be tightened - but it is still sent rather than
    /// derived, for the same reason: it is clamped to the full image, which the
    /// common prefix does not describe.
    ///
    /// It is where the remaining tiled-versus-whole cost lives. One pixel of
    /// widening crosses a 32-tile chunk boundary, so an interior tile resolves
    /// 6 chunks per axis instead of 4 and every seam chunk is resolved by both
    /// neighbours - 1.89x `resolveChunk` calls, measured. That is structural
    /// rather than a defect: a rock one pixel outside genuinely owes this tile
    /// pixels, and knowing whether it exists means resolving its chunk.
    ///
    /// The three THRESHOLDED ores ignore it - they paint one pixel each and
    /// sweep the request's own box.
    ///
    /// For an untiled render this is the pixel box itself.
    pub placement_sweep_box: [f64; 4],
}

impl VulcanusParams {
    /// One bearing's `(sin, cos)`, by name rather than by index.
    #[must_use]
    pub fn bearing(&self, which: VulcanusBearing) -> (f64, f64) {
        self.trig[which as usize]
    }
}

fn u32_at(bytes: &[u8], offset: usize) -> u32 {
    u32::from_le_bytes([
        bytes[offset],
        bytes[offset + 1],
        bytes[offset + 2],
        bytes[offset + 3],
    ])
}

fn f64_at(bytes: &[u8], offset: usize) -> f64 {
    let mut buf = [0u8; 8];
    buf.copy_from_slice(&bytes[offset..offset + 8]);
    f64::from_le_bytes(buf)
}

/// Decode a request.
///
/// # Errors
///
/// Returns a [`Status`] rather than panicking, for every case a caller can
/// cause: a short buffer, a wrong magic or version, an unknown planet, or a
/// declared block length that disagrees with the planet's.
pub fn decode(bytes: &[u8]) -> Result<Request, Status> {
    if bytes.len() < COMMON_BYTES {
        return Err(Status::ShortBuffer);
    }
    if u32_at(bytes, 0) != MAGIC {
        return Err(Status::BadMagic);
    }
    if u32_at(bytes, 4) != ABI_VERSION {
        return Err(Status::BadVersion);
    }

    let planet = u32_at(bytes, 8);
    let declared = u32_at(bytes, 28) as usize;
    // The length is checked against the planet BEFORE the buffer, so a writer
    // that sent a Fulgora block under a Vulcanus planet code is a length error
    // rather than a short buffer - which says which side is wrong.
    let expected = match planet {
        PLANET_FULGORA => FULGORA_PARAMS_BYTES,
        PLANET_VULCANUS => VULCANUS_PARAMS_BYTES,
        _ => return Err(Status::UnsupportedPlanetOrView),
    };
    if declared != expected {
        return Err(Status::BadParamsLength);
    }
    if bytes.len() < COMMON_BYTES + expected {
        return Err(Status::ShortBuffer);
    }

    let p = COMMON_BYTES;
    let params = match planet {
        PLANET_FULGORA => Params::Fulgora(FulgoraParams {
            islands_frequency: f64_at(bytes, p),
            islands_size: f64_at(bytes, p + 8),
            sin_start: f64_at(bytes, p + 16),
            cos_start: f64_at(bytes, p + 24),
            sin_vault: f64_at(bytes, p + 32),
            cos_vault: f64_at(bytes, p + 40),
        }),
        _ => {
            let mut trig = [(0.0, 0.0); VULCANUS_BEARINGS];
            for (i, slot) in trig.iter_mut().enumerate() {
                let at = p + 88 + i * 16;
                *slot = (f64_at(bytes, at), f64_at(bytes, at + 8));
            }
            let mut cell_query_box = [0.0; 4];
            for (i, slot) in cell_query_box.iter_mut().enumerate() {
                *slot = f64_at(bytes, p + 248 + i * 8);
            }
            let mut placement_sweep_box = [0.0; 4];
            for (i, slot) in placement_sweep_box.iter_mut().enumerate() {
                *slot = f64_at(bytes, p + 280 + i * 8);
            }
            Params::Vulcanus(VulcanusParams {
                volcanism_frequency: f64_at(bytes, p),
                volcanism_size: f64_at(bytes, p + 8),
                temperature_bias: f64_at(bytes, p + 16),
                tungsten_frequency: f64_at(bytes, p + 24),
                tungsten_size: f64_at(bytes, p + 32),
                coal_frequency: f64_at(bytes, p + 40),
                coal_size: f64_at(bytes, p + 48),
                calcite_frequency: f64_at(bytes, p + 56),
                calcite_size: f64_at(bytes, p + 64),
                sulfur_frequency: f64_at(bytes, p + 72),
                sulfur_size: f64_at(bytes, p + 80),
                trig,
                cell_query_box,
                placement_sweep_box,
            })
        }
    };

    Ok(Request {
        planet,
        view: u32_at(bytes, 12),
        seed0: u32_at(bytes, 16),
        width: u32_at(bytes, 20),
        height: u32_at(bytes, 24),
        origin_x: f64_at(bytes, 32),
        origin_y: f64_at(bytes, 40),
        tiles_per_pixel: f64_at(bytes, 48),
        params,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn header(planet: u32, params_bytes: usize) -> Vec<u8> {
        let mut b = vec![0u8; COMMON_BYTES + params_bytes];
        b[0..4].copy_from_slice(&MAGIC.to_le_bytes());
        b[4..8].copy_from_slice(&ABI_VERSION.to_le_bytes());
        b[8..12].copy_from_slice(&planet.to_le_bytes());
        b[16..20].copy_from_slice(&2_967_702_466u32.to_le_bytes());
        b[20..24].copy_from_slice(&8u32.to_le_bytes());
        b[24..28].copy_from_slice(&4u32.to_le_bytes());
        b[28..32].copy_from_slice(&(params_bytes as u32).to_le_bytes());
        b[32..40].copy_from_slice(&(-512.5f64).to_le_bytes());
        b[40..48].copy_from_slice(&256.25f64.to_le_bytes());
        b[48..56].copy_from_slice(&2.0f64.to_le_bytes());
        b
    }

    fn good_fulgora() -> Vec<u8> {
        let mut b = header(PLANET_FULGORA, FULGORA_PARAMS_BYTES);
        b[56..64].copy_from_slice(&1.0f64.to_le_bytes());
        b[64..72].copy_from_slice(&1.0f64.to_le_bytes());
        b
    }

    fn good_vulcanus() -> Vec<u8> {
        header(PLANET_VULCANUS, VULCANUS_PARAMS_BYTES)
    }

    #[test]
    fn round_trips_every_common_field_to_its_own_offset() {
        let r = decode(&good_fulgora()).expect("should decode");
        // A seed above 2^31 on purpose: it is what a real Fulgora surface seed
        // looks like, and reading it as an i32 somewhere would show here.
        assert_eq!(r.seed0, 2_967_702_466);
        assert_eq!(r.width, 8);
        assert_eq!(r.height, 4);
        assert_eq!(r.origin_x, -512.5);
        assert_eq!(r.origin_y, 256.25);
        assert_eq!(r.tiles_per_pixel, 2.0);
        match r.params {
            Params::Fulgora(f) => {
                assert_eq!(f.islands_frequency, 1.0);
                assert_eq!(f.islands_size, 1.0);
            }
            Params::Vulcanus(_) => panic!("wrong block decoded"),
        }
    }

    /// A Fulgora request is still 104 bytes, which is what v1's was.
    ///
    /// Not a coincidence worth relying on, but worth pinning: it means the
    /// v2 split cost Fulgora nothing, and if someone later "tidies" the common
    /// prefix this says so.
    ///
    /// **A Vulcanus request has grown twice with no version bump** - 304 -> 336
    /// when the cliff view landed, 336 -> 368 when the rock and resource
    /// overlays did. That is what a per-planet block is FOR: the prefix
    /// declares its own length, `BadParamsLength` refuses a writer that
    /// disagrees, and Fulgora's request has not moved a byte through either.
    /// The two halves ship together and
    /// `test/fixtures/wasm-request.v2.json` pins the encoding, so there is no
    /// third party to keep compatible.
    #[test]
    fn the_split_left_a_fulgora_request_the_size_it_was_in_v1() {
        assert_eq!(COMMON_BYTES + FULGORA_PARAMS_BYTES, 104);
        assert_eq!(COMMON_BYTES + VULCANUS_PARAMS_BYTES, 368);
        assert_eq!(REQUEST_BYTES, 368);
    }

    /// Each failure mode has its OWN code, so a caller can tell "you sent an
    /// old version" from "you sent nothing".
    #[test]
    fn every_rejection_has_its_own_status() {
        assert_eq!(decode(&[]), Err(Status::ShortBuffer));
        assert_eq!(decode(&[0u8; COMMON_BYTES - 1]), Err(Status::ShortBuffer));

        let mut b = good_fulgora();
        b[0] ^= 0xff;
        assert_eq!(decode(&b), Err(Status::BadMagic));

        let mut b = good_fulgora();
        b[4..8].copy_from_slice(&(ABI_VERSION + 1).to_le_bytes());
        assert_eq!(decode(&b), Err(Status::BadVersion));

        let mut b = good_fulgora();
        b[8..12].copy_from_slice(&99u32.to_le_bytes());
        assert_eq!(decode(&b), Err(Status::UnsupportedPlanetOrView));

        // A declared length that is not this planet's.
        let mut b = good_fulgora();
        b[28..32].copy_from_slice(&(FULGORA_PARAMS_BYTES as u32 + 8).to_le_bytes());
        assert_eq!(decode(&b), Err(Status::BadParamsLength));

        // v1's writer sent a zero in that slot. Under v2 it would fail on the
        // version word first, but if only the length word were stale this is
        // what it looks like.
        let mut b = good_fulgora();
        b[28..32].copy_from_slice(&0u32.to_le_bytes());
        assert_eq!(decode(&b), Err(Status::BadParamsLength));
    }

    /// The Vulcanus planet code with a correctly declared but ABSENT block is a
    /// short buffer, not a silent read of whatever follows.
    #[test]
    fn a_declared_block_that_is_not_there_is_a_short_buffer() {
        let mut b = good_vulcanus();
        b.truncate(COMMON_BYTES + VULCANUS_PARAMS_BYTES - 1);
        assert_eq!(decode(&b), Err(Status::ShortBuffer));
    }

    /// A longer buffer decodes fine - anything past the declared block belongs
    /// to a future tail.
    #[test]
    fn a_longer_buffer_is_accepted() {
        let mut b = good_fulgora();
        b.extend_from_slice(&[0xab; 32]);
        assert!(decode(&b).is_ok());
    }

    /// The Fulgora fields do not overlap, which a table of hand-written offsets
    /// can get wrong in a way that still decodes.
    #[test]
    fn no_two_fulgora_fields_share_an_offset() {
        let mut b = good_fulgora();
        let values = [11.0f64, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0];
        for (i, v) in values.iter().enumerate() {
            let at = 32 + i * 8;
            b[at..at + 8].copy_from_slice(&v.to_le_bytes());
        }
        let r = decode(&b).expect("should decode");
        let Params::Fulgora(f) = r.params else {
            panic!("wrong block")
        };
        assert_eq!(
            [
                r.origin_x,
                r.origin_y,
                r.tiles_per_pixel,
                f.islands_frequency,
                f.islands_size,
                f.sin_start,
                f.cos_start,
                f.sin_vault,
                f.cos_vault,
            ],
            values
        );
    }

    /// The same for Vulcanus's 39 fields, which is where a duplicated offset is
    /// most likely and least visible.
    ///
    /// A distinct value into every slot, all read back - so a pair of fields
    /// sharing an offset shows up as two equal values where the input had none.
    /// The two boxes are adjacent and the same shape, which is exactly the pair
    /// most likely to be wired to one another.
    #[test]
    fn no_two_vulcanus_fields_share_an_offset() {
        let mut b = good_vulcanus();
        // 39 distinct values: 11 scalars, 20 trig components, 8 box edges.
        for i in 0..39 {
            let at = COMMON_BYTES + i * 8;
            let v = 100.0f64 + i as f64;
            b[at..at + 8].copy_from_slice(&v.to_le_bytes());
        }
        let r = decode(&b).expect("should decode");
        let Params::Vulcanus(v) = r.params else {
            panic!("wrong block")
        };
        let mut got = vec![
            v.volcanism_frequency,
            v.volcanism_size,
            v.temperature_bias,
            v.tungsten_frequency,
            v.tungsten_size,
            v.coal_frequency,
            v.coal_size,
            v.calcite_frequency,
            v.calcite_size,
            v.sulfur_frequency,
            v.sulfur_size,
        ];
        for (sin, cos) in v.trig {
            got.push(sin);
            got.push(cos);
        }
        got.extend_from_slice(&v.cell_query_box);
        got.extend_from_slice(&v.placement_sweep_box);
        let want: Vec<f64> = (0..39).map(|i| 100.0 + i as f64).collect();
        assert_eq!(got, want);
    }

    /// The ten bearings are addressed by NAME, and the names map to the slots
    /// the layout table says.
    ///
    /// Two bearings swapped rotates the planet's biomes and produces a map that
    /// looks entirely reasonable, so this is checked directly rather than left
    /// to a render comparison.
    #[test]
    fn each_bearing_reads_its_own_pair() {
        let mut b = good_vulcanus();
        for i in 0..VULCANUS_BEARINGS {
            let at = COMMON_BYTES + 88 + i * 16;
            b[at..at + 8].copy_from_slice(&(i as f64).to_le_bytes());
            b[at + 8..at + 16].copy_from_slice(&(-(i as f64)).to_le_bytes());
        }
        let Params::Vulcanus(v) = decode(&b).expect("should decode").params else {
            panic!("wrong block")
        };
        for (i, which) in [
            VulcanusBearing::SpawnAshlands,
            VulcanusBearing::SpawnMountains,
            VulcanusBearing::SpawnBasalts,
            VulcanusBearing::BiomeVolcanoSpot,
            VulcanusBearing::BiomeProtector,
            VulcanusBearing::ResourceTungsten,
            VulcanusBearing::ResourceCoal,
            VulcanusBearing::ResourceCalcite,
            VulcanusBearing::ResourceSulfurFar,
            VulcanusBearing::ResourceSulfurNear,
        ]
        .into_iter()
        .enumerate()
        {
            assert_eq!(v.bearing(which), (i as f64, -(i as f64)), "{which:?}");
        }
    }
}
