//! The request encoding and the render buffer - the whole of the boundary's
//! data layout, and nothing that computes anything.
//!
//! Design record: section 6 of
//! `docs/superpowers/specs/2026-08-16-rust-wasm-noise-engine-design.md`.
//!
//! ## Why hand-written on both sides
//!
//! A TypeScript writer and a Rust reader, both by hand, with no dependency
//! either side. The alternative - a schema compiler - would add a build step to
//! a repo whose whole deployment story is that `vp build` needs no non-JS step,
//! and a generated reader is not obviously easier to review than 40 lines of
//! `from_le_bytes`.
//!
//! What keeps them in step instead:
//!
//! - **A magic word and a version word.** A mismatch is a hard error with its
//!   own status code, not a best-effort parse of whatever arrived.
//! - **A committed round-trip fixture.** `test/fixtures/wasm-request.v1.json`
//!   carries a known request, its exact bytes, and the fields they decode to.
//!   Neither side can change the layout without the other going red, and the
//!   bytes are in the repository rather than being regenerated by the thing
//!   under test.
//! - **The offsets are exported.** `request_len()` and the field table below
//!   are the single definition; the TypeScript writer asserts against them.
//!
//! ## The layout
//!
//! Little-endian throughout - the byte order WebAssembly specifies for its own
//! loads, so no swapping happens on any host.
//!
//! Every `u32` comes first, padded to a multiple of 8, so every `f64` lands on
//! an 8-byte boundary. Nothing here reads through an aligned pointer - the
//! decode is `from_le_bytes` over a slice - so this buys nothing at runtime. It
//! buys a `DataView` writer on the TypeScript side that a reader can check by
//! eye against a hexdump.
//!
//! ```text
//!   0  u32  magic          'FMWR' little-endian
//!   4  u32  abi_version
//!   8  u32  planet         0 = fulgora
//!  12  u32  view           0 = landmask
//!  16  u32  seed0          the SURFACE seed, not the map seed
//!  20  u32  width
//!  24  u32  height
//!  28  u32  reserved       0, and asserted 0 - a future field, not padding
//!  32  f64  origin_x
//!  40  f64  origin_y
//!  48  f64  tiles_per_pixel
//!  56  f64  islands_frequency
//!  64  f64  islands_size
//!  72  f64  sin_start      sine of the starting bearing
//!  80  f64  cos_start
//!  88  f64  sin_vault      sine of the vault bearing (the starting one + 180)
//!  96  f64  cos_vault
//! 104  = REQUEST_BYTES
//! ```
//!
//! **The four trig fields are the unusual part and they are deliberate.** The
//! angle is a per-render constant at every call site, and `starting_spot_at_angle`
//! has no f32 narrowing to absorb a one-ULP `sin` difference - which #270
//! measured really does exist between V8 and the libm `wasm32-unknown-unknown`
//! links. Passing the values instead of the angle makes that impossible rather
//! than unlikely. See `fmw_noise::expressions::starting_spot_at_angle`.

/// `'FMWR'` little-endian.
pub const MAGIC: u32 = 0x5257_4d46;

/// The layout version. Bump it for ANY change to the table above.
pub const ABI_VERSION: u32 = 1;

/// Size of the fixed request header, in bytes.
pub const REQUEST_BYTES: usize = 104;

/// What a decode can go wrong with.
///
/// Returned as a status code rather than trapping. A trap would poison the
/// instance for every later request in that worker, and expected errors are
/// expected - see spec section 6.5.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum Status {
    Ok = 0,
    ShortBuffer = 1,
    BadMagic = 2,
    BadVersion = 3,
    UnsupportedPlanetOrView = 4,
    OutputTooLarge = 5,
    ReservedNotZero = 6,
}

/// A decoded render request.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Request {
    pub planet: u32,
    pub view: u32,
    pub seed0: u32,
    pub width: u32,
    pub height: u32,
    pub origin_x: f64,
    pub origin_y: f64,
    pub tiles_per_pixel: f64,
    pub islands_frequency: f64,
    pub islands_size: f64,
    pub sin_start: f64,
    pub cos_start: f64,
    pub sin_vault: f64,
    pub cos_vault: f64,
}

fn u32_at(bytes: &[u8], offset: usize) -> u32 {
    u32::from_le_bytes([
        bytes[offset],
        bytes[offset + 1],
        bytes[offset + 2],
        bytes[offset + 3],
    ])
}

fn f64_at(bytes: &[u8], offset: usize) -> f64 {
    let mut buf = [0u8; 8];
    buf.copy_from_slice(&bytes[offset..offset + 8]);
    f64::from_le_bytes(buf)
}

/// Decode the fixed header.
///
/// # Errors
///
/// Returns a [`Status`] rather than panicking, for every case a caller can
/// cause: a short buffer, a wrong magic or version, or a reserved word that is
/// not zero.
pub fn decode(bytes: &[u8]) -> Result<Request, Status> {
    if bytes.len() < REQUEST_BYTES {
        return Err(Status::ShortBuffer);
    }
    if u32_at(bytes, 0) != MAGIC {
        return Err(Status::BadMagic);
    }
    if u32_at(bytes, 4) != ABI_VERSION {
        return Err(Status::BadVersion);
    }
    // Asserted rather than skipped. It is a field that does not exist yet, and
    // a writer that puts something there is a writer from a different version
    // than its version word claims.
    if u32_at(bytes, 28) != 0 {
        return Err(Status::ReservedNotZero);
    }
    Ok(Request {
        planet: u32_at(bytes, 8),
        view: u32_at(bytes, 12),
        seed0: u32_at(bytes, 16),
        width: u32_at(bytes, 20),
        height: u32_at(bytes, 24),
        origin_x: f64_at(bytes, 32),
        origin_y: f64_at(bytes, 40),
        tiles_per_pixel: f64_at(bytes, 48),
        islands_frequency: f64_at(bytes, 56),
        islands_size: f64_at(bytes, 64),
        sin_start: f64_at(bytes, 72),
        cos_start: f64_at(bytes, 80),
        sin_vault: f64_at(bytes, 88),
        cos_vault: f64_at(bytes, 96),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn good() -> Vec<u8> {
        let mut b = vec![0u8; REQUEST_BYTES];
        b[0..4].copy_from_slice(&MAGIC.to_le_bytes());
        b[4..8].copy_from_slice(&ABI_VERSION.to_le_bytes());
        b[16..20].copy_from_slice(&2_967_702_466u32.to_le_bytes());
        b[20..24].copy_from_slice(&8u32.to_le_bytes());
        b[24..28].copy_from_slice(&4u32.to_le_bytes());
        b[32..40].copy_from_slice(&(-512.5f64).to_le_bytes());
        b[40..48].copy_from_slice(&256.25f64.to_le_bytes());
        b[48..56].copy_from_slice(&2.0f64.to_le_bytes());
        b[56..64].copy_from_slice(&1.0f64.to_le_bytes());
        b[64..72].copy_from_slice(&1.0f64.to_le_bytes());
        b
    }

    #[test]
    fn round_trips_every_field_to_its_own_offset() {
        let r = decode(&good()).expect("should decode");
        // A seed above 2^31 on purpose: it is what a real Fulgora surface seed
        // looks like, and reading it as an i32 somewhere would show here.
        assert_eq!(r.seed0, 2_967_702_466);
        assert_eq!(r.width, 8);
        assert_eq!(r.height, 4);
        assert_eq!(r.origin_x, -512.5);
        assert_eq!(r.origin_y, 256.25);
        assert_eq!(r.tiles_per_pixel, 2.0);
        assert_eq!(r.islands_frequency, 1.0);
        assert_eq!(r.islands_size, 1.0);
    }

    /// Each failure mode has its OWN code, so a caller can tell "you sent an
    /// old version" from "you sent nothing".
    #[test]
    fn every_rejection_has_its_own_status() {
        assert_eq!(decode(&[]), Err(Status::ShortBuffer));
        assert_eq!(decode(&[0u8; REQUEST_BYTES - 1]), Err(Status::ShortBuffer));

        let mut b = good();
        b[0] ^= 0xff;
        assert_eq!(decode(&b), Err(Status::BadMagic));

        let mut b = good();
        b[4..8].copy_from_slice(&(ABI_VERSION + 1).to_le_bytes());
        assert_eq!(decode(&b), Err(Status::BadVersion));

        let mut b = good();
        b[28] = 1;
        assert_eq!(decode(&b), Err(Status::ReservedNotZero));
    }

    /// A longer buffer decodes fine - the header is fixed and anything after it
    /// belongs to a future tail.
    #[test]
    fn a_longer_buffer_is_accepted() {
        let mut b = good();
        b.extend_from_slice(&[0xab; 32]);
        assert!(decode(&b).is_ok());
    }

    /// The fields do not overlap, which a table of hand-written offsets can get
    /// wrong in a way that still decodes. Writing a distinct value into each
    /// f64 slot and reading them all back is what catches a duplicated offset.
    #[test]
    fn no_two_fields_share_an_offset() {
        let mut b = good();
        let values = [11.0f64, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0];
        for (i, v) in values.iter().enumerate() {
            let at = 32 + i * 8;
            b[at..at + 8].copy_from_slice(&v.to_le_bytes());
        }
        let r = decode(&b).expect("should decode");
        assert_eq!(
            [
                r.origin_x,
                r.origin_y,
                r.tiles_per_pixel,
                r.islands_frequency,
                r.islands_size,
                r.sin_start,
                r.cos_start,
                r.sin_vault,
                r.cos_vault,
            ],
            values
        );
    }
}
